services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - .env

  server:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    env_file:
      - .env