spring:
  application:
    name: history-order-service
  data:
    mongodb:
      database: history_orders
      host: mongodb
      port: 27017
      username: root
      password: secret
      uri: mongodb://root:secret@mongodb:27017
  threads:
    virtual:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka:passw0rd@discovery-server:8761/eureka/
server:
  port: 0
application:
  jwt:
    secret: verysecretkeyWhichIsVeryLongAndHardToGuessSoYouShouldChangeItPleaseAndThankYou
    header: Authorization
    prefix: Bearer
    expiration: 86400000
api:
  key:
    self: HISTORY_ORDER_SERVICE_TOKEN
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
loki:
  url: http://loki:3100/loki/api/v1/push
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  observations:
    key-values:
      application: api-gateway
  tracing:
    sampling:
      probability: 1.0