spring:
  application:
    name: history-order-service
  data:
    mongodb:
      database: history_orders
      host: localhost
      port: 27017
      username: root
      password: secret
      uri: mongodb://root:secret@localhost:27017
  threads:
    virtual:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0
application:
  jwt:
    secret: verysecretkeyWhichIsVeryLongAndHardToGuessSoYouShouldChangeItPleaseAndThankYou
    header: Authorization
    prefix: Bearer
    expiration: 86400000
api:
  key:
    self: HISTORY_ORDER_SERVICE_TOKEN