spring:
  application:
    name: history-order-service
  data:
    mongodb:
      database: history_orders
      host: localhost
      port: 55486
      username: root
      password: secret
      uri: mongodb://root:secret@localhost:55486
  threads:
    virtual:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0