apiVersion: v1
kind: Namespace
metadata:
  name: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: stas230/store-discovery-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: _JAVA_OPTIONS
              value: -Deureka.instance.preferIpAddress=true -Deureka.client.registerWithEureka=false -Deureka.client.fetchRegistry=false -Deureka.client.serviceUrl.defaultZone=http://eureka:passw0rd@discovery-server.default.svc.cluster.local:8761/eureka/

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: default
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    app: discovery-server